### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by LeKristapino** [plataformatec/mail_form#35]
Hi,

The gem is really good though I ran into some problems (I am sort of a beginner in rails) when validating form. I had a hard time finding why my create function with @contact = Contact.new(params[:contact]).deliver always returned Nil object. In SO I was pointed out that ActiveRecord validations are only called on methods like save or valid? so I have to add a conditional statement for everything to work.

This should be a good this to add in your docs or make the deliver method call the ActiveRecord validations in future releases.

Hope it helps.

**Comment by carlosantoniodasilva** [comment]
Mail Form should only trigger the notification in case the object is really valid, so calling `deliver` does check for `valid?` before proceeding. I'm not sure that was the case of your issue, but it seems that calling this:

```ruby
@contact = Contact.new(params[:contact]).deliver
```

could indeed return `nil`, as the `deliver` method does not return the instance itself. I believe you should write this code like this:

```ruby
@contact = Contact.new(params[:contact])
@contact.deliver
```

If you need the variable `@contact` for further processing somehow. Again, I may have misunderstood your question/issue, so please let me know if I did. Thanks!

**Comment by LeKristapino** [comment]
Isn't The Contact.new an instance itself and @contact just the variable name where this instance is stored. Well I mean- in terms of Activemodel I thought that the deliver method is something similar to creat where as now it seems to be more like a new-save type of method (just instead of save it is deliver). But thank you for your answer, I'll keep this in mind!

**Comment by carlosantoniodasilva** [comment]
Yes, it's like `save` indeed, in fact `save` is an alias of `deliver`, so both should work the same.
