### ISSUE TITLE
Add support for deliver_later from Rails 4.2

### ISSUE THREAD

**Issue by leosmeira** [plataformatec/mail_form#36]

**Comment by passalini** [comment]
+1

**Comment by Lordnibbler** [comment]
+2

**Comment by lucasmazza** [comment]
Related to #33.

**Comment by lucasmazza** [comment]
1.5.1 is out using `deliver_now` so we won't get the deprecation notice anymore. To use `deliver_later` will require further changes to get the ActionMailer -> ActiveJob serialization working which may require some breaking changes, so let's save it for a future release.
