### ISSUE TITLE
deliver_now ?

### ISSUE THREAD

**Issue by samstickland** [plataformatec/mail_form#39]
Any plans to update this to use deliver_now in rails 4?

**Comment by carlosantoniodasilva** [comment]
1.5.1 was released yesterday with support to Rails 4, check #36 for more info.

@lucasmazza it seems the tag/commit was not pushed, mind checking?

**Comment by samstickland** [comment]
Perfect :)

**Comment by lucasmazza** [comment]
@carlosantoniodasilva just pushed it :+1:

**Comment by carlosantoniodasilva** [comment]
:heart:

On Sun, Apr 12, 2015 at 4:00 PM, Lucas Mazza <notifications@github.com>
wrote:

> @carlosantoniodasilva <https://github.com/carlosantoniodasilva> just
> pushed it [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plataformatec/mail_form/issues/39#issuecomment-92100541>
> .
>



-- 
At.
Carlos Antonio
