### ISSUE TITLE
How to make it working with sidekiq worker?

### ISSUE THREAD

**Issue by railsr** [plataformatec/mail_form#41]
Is it possible to make this gem working async as a sidekiq worker?

I got this error 
```2015-07-24T12:35:26.451Z 1877 TID-ovhe84764 WARN: NoMethodError: private method `new' called for ContactWorker:Class```

**Comment by georgeguimaraes** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!
