### ISSUE TITLE
Is it possible to send to multiple addresses?

### ISSUE THREAD

**Issue by say8425** [plataformatec/mail_form#42]
```ruby
def headers
    {:subject => %("#{title}"),
     :to => "{'test1@gamil.com',test2@gmail.com'}",
     :from => %("#{name}" <#{email}>)}
end
```

I try it but it's fail. First address was sent, but maybe second looks did not.
Any method is existed?

**Comment by nashby** [comment]
> The list of emails can be an array of email addresses or a single string with the addresses separated by commas.

http://guides.rubyonrails.org/action_mailer_basics.html

**Comment by say8425** [comment]
```ruby
def headers
    {:subject => %("#{title}"),
     :to => %w(test1@gamil.com test2@gmail.com),
     :from => %("#{name}" <#{email}>)}
end
```

Thanks to you, I could completely code.
I wish this example helps.
