### ISSUE TITLE
Docs and `mail_attachments`

### ISSUE THREAD

**Issue by prwhitehead** [plataformatec/mail_form#44]
Hey, it took me a while to work out why attachments were not being attached. 

I had read the docs, but there was no mention of having to define `mail_attachments` on the form class. In the example where you mention attachments it would be good to mention that the following is also required (I only happened to find it by code diving and throwing byebugs in the gem): 

    class Form < Mailer::Base

         attributes :image, validate: true, attactment: true

         def mail_attachments
             [:image]
         end
    end

**Comment by nashby** [comment]
@prwhitehead hey, I think you have ti define `mail_attachments ` method because you have a typo in your `attactment: true`. It should be `attachment`

**Comment by prwhitehead** [comment]
Oh. My. God. That's embarrassing!

Thank you.
