### ISSUE TITLE
How do I send an email with attachment?

### ISSUE THREAD

**Issue by fredmurakawa** [plataformatec/mail_form#58]
I'm trying to send an email with attachment but it's not working.

In the form, I used:

<%= simple_form_for @comprovante, html: { multipart: true }, defaults: { wrapper_html: { class: 'form-group' }, input_html: { class: 'form-control' } } do |f| %>
       
     <%= f.file_field :file %>

<% end %>

I receive the email but there is nothing attached.

***Email`s Body***
Name: John
Email: test@email.com
Message: Testing email
File: #<ActionDispatch::Http::UploadedFile:0x00007fc9094557c0>

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
